### ISSUE TITLE
MY STORY SECTION

### ISSUE THREAD

**Issue by greghunt** [greghunt/freedom13#3]
- add margin to the text area to keep the whole layout tighter and more readable. 
- Turn photo areas into sliders (images are in SITEFILES)

**Comment by melanieleduc** [comment]
![mystory](https://cloud.githubusercontent.com/assets/15948149/11942002/8bb43b94-a801-11e5-83ad-1cfb9f235c82.PNG)

**Comment by melanieleduc** [comment]
my res is 1920 wide fyi
