### ISSUE TITLE
Formatting issues: screenshots

### ISSUE THREAD

**Issue by melanieleduc** [greghunt/freedom13#9]
![first section](https://cloud.githubusercontent.com/assets/15948149/11942019/ac725500-a801-11e5-91a4-b4f89ea8aa6c.PNG)

![section2](https://cloud.githubusercontent.com/assets/15948149/11942021/b0881efe-a801-11e5-9ce3-7c6ddf386e68.PNG)

**Comment by greghunt** [comment]
I'm leaving this one open for now, it's specific to large res so I'll have to wait to test.
